spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cpt202?useSSL=false&serverTimezone=UTC
    username: root
    password: luhan7110420

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true